### ISSUE TITLE
Customize camera-view design

### ISSUE THREAD

**Issue by dhavrosh** [BlinkID/blinkid-react-native-ios#5]
Hey guys,

I wonder if I can customize a camera-view design of blinkid-module, 
Does anybody know if it's possible?

**Comment by juraskrlec** [comment]
Hi @dhavrosh 
for now, in our component, there is only default implementation of ScanningViewController with our default design. You can create your own design withers  overla ViewController and add it as overlay controller like [here](https://github.com/BlinkID/blinkid-ios/wiki/Customizing-Camera-UI) and

**Comment by dhavrosh** [comment]
Thanks
