### ISSUE TITLE
Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by dhavrosh** [BlinkID/blinkid-react-native-ios#6]
Hey Guys,
I'm trying to integrate your module with my ios-app, I've followed all your requirements but during building I got the next errors:

```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_PPCameraCoordinator", referenced from:
      objc-class-ref in libBlinkIDReactNative.a(BlinkIDReactNative.o)
  "_OBJC_CLASS_$_PPDocumentFaceRecognizerResult", referenced from:
      objc-class-ref in libBlinkIDReactNative.a(BlinkIDReactNative.o)
  "_OBJC_CLASS_$_PPDocumentFaceRecognizerSettings", referenced from:
      objc-class-ref in libBlinkIDReactNative.a(BlinkIDReactNative.o)
  "_OBJC_CLASS_$_PPEudlRecognizerResult", referenced from:
      objc-class-ref in libBlinkIDReactNative.a(BlinkIDReactNative.o)
  "_OBJC_CLASS_$_PPEudlRecognizerSettings", referenced from:
      objc-class-ref in libBlinkIDReactNative.a(BlinkIDReactNative.o)
```
I've tried to add blink library manually, not by react-native link, but got the same result.
Maybe somebody know how to solve it?

PS: Despite the build failed I can render your demo app. But the setBlinkIDLicenseKey function calls the method of empty native module in your project.

**Comment by dhavrosh** [comment]
What I needed is to install Git Large File Storage

**Comment by yummyelin** [comment]
@dhavrosh hi, I met the same issue, could you explain more?

**Comment by dhavrosh** [comment]
Hey @yummyelin, you have a good enough description on main page
https://github.com/BlinkID/blinkid-react-native-ios
'Installation with CocoaPods' section
